package DegreesApp;

/**
* DegreesApp/DegreesAppHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Programms/Eclipse_Java/eclipse-workspace/Exam_1/Degrees.idl
* Friday, March 18, 2022 8:43:03 AM CST
*/

public final class DegreesAppHolder implements org.omg.CORBA.portable.Streamable
{
  public DegreesApp.DegreesApp value = null;

  public DegreesAppHolder ()
  {
  }

  public DegreesAppHolder (DegreesApp.DegreesApp initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DegreesApp.DegreesAppHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DegreesApp.DegreesAppHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DegreesApp.DegreesAppHelper.type ();
  }

}
