package DegreesApp;


/**
* DegreesApp/DegreesAppHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Programms/Eclipse_Java/eclipse-workspace/Exam_1/Degrees.idl
* Friday, March 18, 2022 8:43:03 AM CST
*/

abstract public class DegreesAppHelper
{
  private static String  _id = "IDL:DegreesApp/DegreesApp:1.0";

  public static void insert (org.omg.CORBA.Any a, DegreesApp.DegreesApp that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DegreesApp.DegreesApp extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DegreesApp.DegreesAppHelper.id (), "DegreesApp");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DegreesApp.DegreesApp read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DegreesAppStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DegreesApp.DegreesApp value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DegreesApp.DegreesApp narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DegreesApp.DegreesApp)
      return (DegreesApp.DegreesApp)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DegreesApp._DegreesAppStub stub = new DegreesApp._DegreesAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DegreesApp.DegreesApp unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DegreesApp.DegreesApp)
      return (DegreesApp.DegreesApp)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DegreesApp._DegreesAppStub stub = new DegreesApp._DegreesAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
