package DegreesApp;


/**
* DegreesApp/DegreesAppPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Programms/Eclipse_Java/eclipse-workspace/Exam_1/Degrees.idl
* Friday, March 18, 2022 8:43:03 AM CST
*/

public abstract class DegreesAppPOA extends org.omg.PortableServer.Servant
 implements DegreesApp.DegreesAppOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCelcius", new java.lang.Integer (0));
    _methods.put ("getFahrenheit", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DegreesApp/DegreesApp/getCelcius
       {
         double input = in.read_double ();
         String $result = null;
         $result = this.getCelcius (input);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DegreesApp/DegreesApp/getFahrenheit
       {
         double input = in.read_double ();
         String $result = null;
         $result = this.getFahrenheit (input);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DegreesApp/DegreesApp:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DegreesApp _this() 
  {
    return DegreesAppHelper.narrow(
    super._this_object());
  }

  public DegreesApp _this(org.omg.CORBA.ORB orb) 
  {
    return DegreesAppHelper.narrow(
    super._this_object(orb));
  }


} // class DegreesAppPOA
