package DegreesApp;


/**
* DegreesApp/DegreesAppOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Programms/Eclipse_Java/eclipse-workspace/Exam_1/Degrees.idl
* Friday, March 18, 2022 8:43:03 AM CST
*/

public interface DegreesAppOperations 
{
  String getCelcius (double input);
  String getFahrenheit (double input);
} // interface DegreesAppOperations
